MaterialsNameCHS = {
    "长生仙": "AbidingAngelfish",
    "冒险阅历": "AdventureEXP",
    "冒险家的经验": "AdventurersExperience",
    "特工祭刀": "AgentsSacrificialKnife",
    "燃愿玛瑙块": "AgnidusAgateChunk",
    "燃愿玛瑙断片": "AgnidusAgateFragment",
    "燃愿玛瑙": "AgnidusAgateGemstone",
    "燃愿玛瑙碎屑": "AgnidusAgateSliver",
    "蓝染花鳉": "AizenMedaka",
    "赤魔王": "AkaiMaou",
    "赤穗酒枡": "AkosSakeVessel",
    "「溶媒」": "Alkahest",
    "杏仁": "Almond",
    "天云草实": "AmakumoFruit",
    "紫晶块": "AmethystLump",
    "苹果": "Apple",
    "孔雀木": "AraliaWood",
    "灰烬之心": "AshenHeart",
    "培根": "Bacon",
    "竹节": "BambooSegment",
    "竹笋": "BambooShoot",
    "玄岩之塔": "BasaltPillar",
    "树莓": "Berry",
    "斗棘鱼": "Betta",
    "桦木": "BirchWood",
    "鸟蛋": "BirdEgg",
    "漆黑陨铁的一角": "BitofAerosiderite",
    "苦炮鲀": "BitterPufferfish",
    "黑铜号角": "BlackBronzeHorn",
    "黑晶号角": "BlackCrystalHorn",
    "血玉之枝": "BloodjadeBranch",
    "蓝色染料": "BlueDye",
    "凛风奔狼的断牙": "BorealWolfsBrokenFang",
    "凛风奔狼的裂齿": "BorealWolfsCrackedTooth",
    "凛风奔狼的始龀": "BorealWolfsMilkTooth",
    "凛风奔狼的怀乡": "BorealWolfsNostalgia",
    "璀璨原钻块": "BrilliantDiamondChunk",
    "璀璨原钻断片": "BrilliantDiamondFragment",
    "璀璨原钻": "BrilliantDiamondGemstone",
    "璀璨原钻碎屑": "BrilliantDiamondSliver",
    "流纹褐蝶鱼": "BrownShirakodai",
    "黄油": "Butter",
    "蝴蝶翅膀": "ButterflyWings",
    "卷心菜": "Cabbage",
    "嘟嘟莲": "CallaLily",
    "胡萝卜": "Carrot",
    "塞西莉亚花": "Cecilia",
    "狮牙斗士的铁链": "ChainsoftheDandelionGladiator",
    "混沌枢纽": "ChaosAxis",
    "混沌回路": "ChaosCircuit",
    "混沌炉心": "ChaosCore",
    "混沌装置": "ChaosDevice",
    "混沌机关": "ChaosGear",
    "混沌真眼": "ChaosOculus",
    "奶酪": "Cheese",
    "「冷鲜肉」": "ChilledMeat",
    "漆黑陨铁的一块": "ChunkofAerosiderite",
    "净水之心": "CleansingHeart",
    "好感经验": "CompanionshipEXP",
    "隐兽指爪": "ConcealedClaw",
    "隐兽鬼爪": "ConcealedTalon",
    "隐兽利爪": "ConcealedUnguis",
    "远海夷地的瑚枝": "CoralBranchofaDistantSea",
    "石珀": "CorLapis",
    "螃蟹": "Crab",
    "蟹黄": "CrabRoe",
    "奶油": "Cream",
    "智识之冕": "CrownofInsight",
    "水晶块": "CrystalChunk",
    "晶核": "CrystalCore",
    "水晶宴": "Crystalfish",
    "晶凝之华": "CrystallineBloom",
    "晶化骨髓": "CrystalMarrow",
    "水晶棱镜": "CrystalPrism",
    "萃华木": "CuihuaWood",
    "破损的面具": "DamagedMask",
    "蒲公英籽": "DandelionSeed",
    "夤夜刻像": "DarkStatuette",
    "擒霞客": "Dawncatcher",
    "地脉的旧枝": "DeadLeyLineBranch",
    "地脉的枯叶": "DeadLeyLineLeaves",
    "幽邃刻像": "DeathlyStatuette",
    "高塔孤王的残垣": "DebrisofDecarabiansCity",
    "血斛": "Dendrobium",
    "排异之露": "DewofRepudiation",
    "黯淡棱镜": "DismalPrism",
    "孤云寒林的神体": "DivineBodyfromGuyun",
    "导能绘卷": "DiviningScroll",
    "龙王之冕": "DragonLordsCrown",
    "狮牙斗士的理想": "DreamoftheDandelionGladiator",
    "鱼干": "DriedFish",
    "东风之爪": "DvalinsClaw",
    "东风之翎": "DvalinsPlume",
    "东风的吐息": "DvalinsSigh",
    "电气水晶": "ElectroCrystal",
    "海皇香脂": "EmperorsBalsam",
    "原素花蜜": "EnergyNectar",
    "精锻用杂矿": "EnhancementOre",
    "常燃火种": "EverflameSeed",
    "布匹": "Fabric",
    "名刀镡": "FamedHandguard",
    "腐殖龙髓": "FesteringDragonMarrow",
    "狮牙斗士的枷锁": "FettersoftheDandelionGladiator",
    "精锻用良矿": "FineEnhancementOre",
    "牢固的箭簇": "FirmArrowhead",
    "杉木": "FirWood",
    "鱼肉": "Fish",
    "烈焰花花蕊": "FlamingFlowerStamen",
    "面粉": "Flour",
    "幽灯蕈": "FluorescentFungus",
    "禁咒绘卷": "ForbiddenCurseScroll",
    "石化的骨片": "FossilizedBoneShard",
    "禽肉": "Fowl",
    "脆弱的骨片": "FragileBoneShard",
    "高塔孤王的断片": "FragmentofDecarabiansEpic",
    "「童真的断篇」": "FragmentsofInnocence",
    "垂香木": "FragrantCedarWood",
    "青蛙": "Frog",
    "鎏金之鳞": "GildedScale",
    "琉璃百合": "GlazeLily",
    "琉璃花鳉": "GlazeMedaka",
    "晦暗刻像": "GloomyStatuette",
    "远海夷地的金枝": "GoldenBranchofaDistantSea",
    "金赤假龙": "GoldenKoi",
    "攫金鸦印": "GoldenRavenInsignia",
    "漆黑陨铁的一粒": "GrainofAerosiderite",
    "「诗文」的指引": "GuidetoBallad",
    "「勤劳」的指引": "GuidetoDiligence",
    "「风雅」的指引": "GuidetoElegance",
    "「自由」的指引": "GuidetoFreedom",
    "「黄金」的指引": "GuidetoGold",
    "「天光」的指引": "GuidetoLight",
    "「繁荣」的指引": "GuidetoProsperity",
    "「抗争」的指引": "GuidetoResistance",
    "「浮世」的指引": "GuidetoTransience",
    "火腿": "Ham",
    "沉重号角": "HeavyHorn",
    "狱火之蝶": "HellfireButterfly",
    "大英雄的经验": "HerosWit",
    "极寒之核": "HoarfrostCore",
    "马尾": "Horsetail",
    "猎兵祭刀": "HuntersSacrificialKnife",
    "飓风之种": "HurricaneSeed",
    "督察长祭刀": "InspectorsSacrificialKnife",
    "铁块": "IronChunk",
    "远海夷地的琼枝": "JadeBranchofaDistantSea",
    "果酱": "Jam",
    "远海夷地的玉枝": "JeweledBranchofaDistantSea",
    "绝云椒椒": "JueyunChili",
    "未熟之玉": "JuvenileJade",
    "影打刀镡": "KageuchiHandguard",
    "灯纸纤维": "LanternFiber",
    "堇瓜": "LavenderMelon",
    "地脉的新芽": "LeyLineSprout",
    "尉官的徽记": "LieutenantsInsignia",
    "雷光棱镜": "LightningPrism",
    "蜥蜴尾巴": "LizardTail",
    "鳅鳅宝玉": "LoachPearl",
    "莲蓬": "LotusHead",
    "发光髓": "LuminescentSpine",
    "孤云寒林的光砂": "LuminousSandsfromGuyun",
    "肺棘鱼": "LungedStickleback",
    "孤云寒林的辉岩": "LustrousStonefromGuyun",
    "魔晶块": "MagicalCrystalChunk",
    "枫木": "MapleWood",
    "魔偶机心": "MarionetteCore",
    "今昔剧画之鬼人": "MaskoftheKijin",
    "今昔剧画之一角": "MaskoftheOne-Horned",
    "今昔剧画之虎啮": "MaskoftheTigersBite",
    "今昔剧画之恶尉": "MaskoftheWickedLieutenant",
    "松茸": "Matsutake",
    "花鳉": "Medaka",
    "牛奶": "Milk",
    "薄荷": "Mint",
    "冰雾花花朵": "MistFlowerCorolla",
    "雾虚草囊": "MistGrass",
    "雾虚花粉": "MistGrassPollen",
    "雾虚灯芯": "MistGrassWick",
    "雾海云间的金丹": "MistVeiledGoldElixir",
    "雾海云间的铅丹": "MistVeiledLeadElixir",
    "雾海云间的汞丹": "MistVeiledMercuryElixir",
    "雾海云间的转还": "MistVeiledPrimoElixir",
    "熔毁之刻": "MoltenMoment",
    "摩拉": "Mora",
    "蘑菇": "Mushroom",
    "精锻用魔矿": "MysticEnhancementOre",
    "生长碧翡块": "NagadusEmeraldChunk",
    "生长碧翡断片": "NagadusEmeraldFragment",
    "生长碧翡": "NagadusEmeraldGemstone",
    "生长碧翡碎屑": "NagadusEmeraldSliver",
    "鸣草": "NakuWeed",
    "鸣神御灵的亲爱": "NarukamisAffection",
    "鸣神御灵的欢喜": "NarukamisJoy",
    "鸣神御灵的勇武": "NarukamisValor",
    "鸣神御灵的明惠": "NarukamisWisdom",
    "夜泊石": "NoctilucousJade",
    "北陆弓原胚": "NorthlanderBowBillet",
    "北陆法器原胚": "NorthlanderCatalystBillet",
    "北陆双手剑原胚": "NorthlanderClaymoreBillet",
    "北陆长柄武器原胚": "NorthlanderPolearmBillet",
    "北陆单手剑原胚": "NorthlanderSwordBillet",
    "破旧的刀镡": "OldHandguard",
    "不祥的面具": "OminousMask",
    "鬼兜虫": "Onikabuto",
    "洋葱": "Onion",
    "御伽木": "OtogiWood",
    "胡椒": "Pepper",
    "恒常机关之心": "PerpetualHeart",
    "慕风蘑菇": "PhilanemoMushroom",
    "「诗文」的哲学": "PhilosophiesofBallad",
    "「勤劳」的哲学": "PhilosophiesofDiligence",
    "「风雅」的哲学": "PhilosophiesofElegance",
    "「自由」的哲学": "PhilosophiesofFreedom",
    "「黄金」的哲学": "PhilosophiesofGold",
    "「天光」的哲学": "PhilosophiesofLight",
    "「繁荣」的哲学": "PhilosophiesofProsperity",
    "「抗争」的哲学": "PhilosophiesofResistance",
    "「浮世」的哲学": "PhilosophiesofTransience",
    "漆黑陨铁的一片": "PieceofAerosiderite",
    "松果": "Pinecone",
    "松木": "PineWood",
    "浮生石片": "PlaustriteShard",
    "偏光棱镜": "PolarizingPrism",
    "土豆": "Potato",
    "原石": "Primogem",
    "坚牢黄玉块": "PrithivaTopazChunk",
    "坚牢黄玉断片": "PrithivaTopazFragment",
    "坚牢黄玉": "PrithivaTopazGemstone",
    "坚牢黄玉碎屑": "PrithivaTopazSliver",
    "炮鲀": "Pufferfish",
    "流纹京紫蝶鱼": "PurpleShirakodai",
    "清心": "Qingxin",
    "白萝卜": "Radish",
    "雷鸣仙": "RaimeiAngelfish",
    "兽肉": "RawMeat",
    "新兵的徽记": "RecruitsInsignia",
    "红色染料": "RedDye",
    "孤云寒林的圣骸": "RelicfromGuyun",
    "稻米": "Rice",
    "兽境王器": "RiftbornRegalia",
    "北风之环": "RingofBoreas",
    "锖假龙": "RustyKoi",
    "绯樱绣球": "SakuraBloom",
    "盐": "Salt",
    "却砂木": "SandbearerWood",
    "珊瑚真珠": "SangoPearl",
    "香肠": "Sausage",
    "高塔孤王的碎梦": "ScatteredPieceofDecarabiansDream",
    "海灵芝": "SeaGanoderma",
    "海草": "Seagrass",
    "封魔绘卷": "SealedScroll",
    "士官的徽记": "SergeantsInsignia",
    "狮牙斗士的镣铐": "ShacklesoftheDandelionGladiator",
    "武炼之魂·孤影": "ShadowoftheWarrior",
    "魔王之刃·残片": "ShardofaFoulLegacy",
    "锐利的箭簇": "SharpArrowhead",
    "微光花蜜": "ShimmeringNectar",
    "哀叙冰玉块": "ShivadaJadeChunk",
    "哀叙冰玉断片": "ShivadaJadeFragment",
    "哀叙冰玉": "ShivadaJadeGemstone",
    "哀叙冰玉碎屑": "ShivadaJadeSliver",
    "虾仁": "ShrimpMeat",
    "霓裳花": "SilkFlower",
    "天原银莲": "SilverLotus",
    "藏银鸦印": "SilverRavenInsignia",
    "史莱姆原浆": "SlimeConcentrate",
    "史莱姆凝液": "SlimeCondensate",
    "史莱姆清": "SlimeSecretions",
    "小灯草": "SmallLampGrass",
    "熏鱼": "SmokedFish",
    "熏禽肉": "SmokedFowl",
    "阴燃之珠": "SmolderingPearl",
    "金鱼草": "Snapdragon",
    "雪中君": "Snowstrider",
    "浮游幽核": "SpectralHeart",
    "浮游干核": "SpectralHusk",
    "浮游晶化核": "SpectralNucleus",
    "北风的魂匣": "SpiritLocketofBoreas",
    "污秽的面具": "StainedMask",
    "星螺": "Starconch",
    "星银矿石": "Starsilver",
    "雷霆数珠": "StormBeads",
    "奇异的「牙齿」": "StrangeTooth",
    "结实的骨片": "SturdyBoneShard",
    "糖": "Sugar",
    "日落果": "Sunsettia",
    "甜甜花": "SweetFlower",
    "甜甜花鳉": "Sweet-FlowerMedaka",
    "北风之尾": "TailofBoreas",
    "「诗文」的教导": "TeachingsofBallad",
    "「勤劳」的教导": "TeachingsofDiligence",
    "「风雅」的教导": "TeachingsofElegance",
    "「自由」的教导": "TeachingsofFreedom",
    "「黄金」的教导": "TeachingsofGold",
    "「天光」的教导": "TeachingsofLight",
    "「繁荣」的教导": "TeachingsofProsperity",
    "「抗争」的教导": "TeachingsofResistance",
    "「浮世」的教导": "TeachingsofTransience",
    "流纹茶蝶鱼": "Tea-ColoredShirakodai",
    "「看得见的风」": "TheVisibleWinds",
    "高塔孤王的破瓦": "TileofDecarabiansTower",
    "豆腐": "Tofu",
    "番茄": "Tomato",
    "寻宝鸦印": "TreasureHoarderInsignia",
    "吞天之鲸·只角": "TuskofMonocerosCaeli",
    "鳗肉": "UnagiMeat",
    "最胜紫晶块": "VajradaAmethystChunk",
    "最胜紫晶断片": "VajradaAmethystFragment",
    "最胜紫晶": "VajradaAmethystGemstone",
    "最胜紫晶碎屑": "VajradaAmethystSliver",
    "落落莓": "Valberry",
    "涤净青金块": "VarunadaLazuriteChunk",
    "涤净青金断片": "VarunadaLazuriteFragment",
    "涤净青金": "VarunadaLazuriteGemstone",
    "涤净青金碎屑": "VarunadaLazuriteSliver",
    "自在松石块": "VayudaTurquoiseChunk",
    "自在松石断片": "VayudaTurquoiseFragment",
    "自在松石": "VayudaTurquoiseGemstone",
    "自在松石碎屑": "VayudaTurquoiseSliver",
    "鸩棘鱼": "VenomspineFish",
    "琉璃袋": "Violetgrass",
    "汲取了生命力的龙牙": "VitalizedDragontooth",
    "流浪者的经验": "WanderersAdvice",
    "历战的箭簇": "WeatheredArrowhead",
    "小麦": "Wheat",
    "白铁块": "WhiteIronChunk",
    "骗骗花蜜": "WhopperflowerNectar",
    "灯芯绒材": "WickMaterial",
    "风车菊": "WindwheelAster",
    "钩钩果": "Wolfhook",
    "黄色染料": "YellowDye",
    "梦见木": "YumemiruWood"
}

MaterialsNameEN = {
    "Abiding Angelfish": "AbidingAngelfish",
    "Adventure EXP": "AdventureEXP",
    "Adventurer's Experience": "AdventurersExperience",
    "Agent's Sacrificial Knife": "AgentsSacrificialKnife",
    "Agnidus Agate Chunk": "AgnidusAgateChunk",
    "Agnidus Agate Fragment": "AgnidusAgateFragment",
    "Agnidus Agate Gemstone": "AgnidusAgateGemstone",
    "Agnidus Agate Sliver": "AgnidusAgateSliver",
    "Aizen Medaka": "AizenMedaka",
    "Akai Maou": "AkaiMaou",
    "Ako's Sake Vessel": "AkosSakeVessel",
    "Alkahest": "Alkahest",
    "Almond": "Almond",
    "Amakumo Fruit": "AmakumoFruit",
    "Amethyst Lump": "AmethystLump",
    "Apple": "Apple",
    "Aralia Wood": "AraliaWood",
    "Ashen Heart": "AshenHeart",
    "Bacon": "Bacon",
    "Bamboo Segment": "BambooSegment",
    "Bamboo Shoot": "BambooShoot",
    "Basalt Pillar": "BasaltPillar",
    "Berry": "Berry",
    "Betta": "Betta",
    "Birch Wood": "BirchWood",
    "Bird Egg": "BirdEgg",
    "Bit of Aerosiderite": "BitofAerosiderite",
    "Bitter Pufferfish": "BitterPufferfish",
    "Black Bronze Horn": "BlackBronzeHorn",
    "Black Crystal Horn": "BlackCrystalHorn",
    "Bloodjade Branch": "BloodjadeBranch",
    "Blue Dye": "BlueDye",
    "Boreal Wolf's Broken Fang": "BorealWolfsBrokenFang",
    "Boreal Wolf's Cracked Tooth": "BorealWolfsCrackedTooth",
    "Boreal Wolf's Milk Tooth": "BorealWolfsMilkTooth",
    "Boreal Wolf's Nostalgia": "BorealWolfsNostalgia",
    "Brilliant Diamond Chunk": "BrilliantDiamondChunk",
    "Brilliant Diamond Fragment": "BrilliantDiamondFragment",
    "Brilliant Diamond Gemstone": "BrilliantDiamondGemstone",
    "Brilliant Diamond Sliver": "BrilliantDiamondSliver",
    "Brown Shirakodai": "BrownShirakodai",
    "Butter": "Butter",
    "Butterfly Wings": "ButterflyWings",
    "Cabbage": "Cabbage",
    "Calla Lily": "CallaLily",
    "Carrot": "Carrot",
    "Cecilia": "Cecilia",
    "Chains of the Dandelion Gladiator": "ChainsoftheDandelionGladiator",
    "Chaos Axis": "ChaosAxis",
    "Chaos Circuit": "ChaosCircuit",
    "Chaos Core": "ChaosCore",
    "Chaos Device": "ChaosDevice",
    "Chaos Gear": "ChaosGear",
    "Chaos Oculus": "ChaosOculus",
    "Cheese": "Cheese",
    "Chilled Meat": "ChilledMeat",
    "Chunk of Aerosiderite": "ChunkofAerosiderite",
    "Cleansing Heart": "CleansingHeart",
    "Companionship EXP": "CompanionshipEXP",
    "Concealed Claw": "ConcealedClaw",
    "Concealed Talon": "ConcealedTalon",
    "Concealed Unguis": "ConcealedUnguis",
    "Coral Branch of a Distant Sea": "CoralBranchofaDistantSea",
    "Cor Lapis": "CorLapis",
    "Crab": "Crab",
    "Crab Roe": "CrabRoe",
    "Cream": "Cream",
    "Crown of Insight": "CrownofInsight",
    "Crystal Chunk": "CrystalChunk",
    "Crystal Core": "CrystalCore",
    "Crystalfish": "Crystalfish",
    "Crystalline Bloom": "CrystallineBloom",
    "Crystal Marrow": "CrystalMarrow",
    "Crystal Prism": "CrystalPrism",
    "Cuihua Wood": "CuihuaWood",
    "Damaged Mask": "DamagedMask",
    "Dandelion Seed": "DandelionSeed",
    "Dark Statuette": "DarkStatuette",
    "Dawncatcher": "Dawncatcher",
    "Dead Ley Line Branch": "DeadLeyLineBranch",
    "Dead Ley Line Leaves": "DeadLeyLineLeaves",
    "Deathly Statuette": "DeathlyStatuette",
    "Debris of Decarabian's City": "DebrisofDecarabiansCity",
    "Dendrobium": "Dendrobium",
    "Dew of Repudiation": "DewofRepudiation",
    "Dismal Prism": "DismalPrism",
    "Divine Body from Guyun": "DivineBodyfromGuyun",
    "Divining Scroll": "DiviningScroll",
    "Dragon Lord's Crown": "DragonLordsCrown",
    "Dream of the Dandelion Gladiator": "DreamoftheDandelionGladiator",
    "Dried Fish": "DriedFish",
    "Dvalin's Claw": "DvalinsClaw",
    "Dvalin's Plume": "DvalinsPlume",
    "Dvalin's Sigh": "DvalinsSigh",
    "Electro Crystal": "ElectroCrystal",
    "Emperor's Balsam": "EmperorsBalsam",
    "Energy Nectar": "EnergyNectar",
    "Enhancement Ore": "EnhancementOre",
    "Everflame Seed": "EverflameSeed",
    "Fabric": "Fabric",
    "Famed Handguard": "FamedHandguard",
    "Festering Dragon Marrow": "FesteringDragonMarrow",
    "Fetters of the Dandelion Gladiator": "FettersoftheDandelionGladiator",
    "Fine Enhancement Ore": "FineEnhancementOre",
    "Firm Arrowhead": "FirmArrowhead",
    "Fir Wood": "FirWood",
    "Fish": "Fish",
    "Flaming Flower Stamen": "FlamingFlowerStamen",
    "Flour": "Flour",
    "Fluorescent Fungus": "FluorescentFungus",
    "Forbidden Curse Scroll": "ForbiddenCurseScroll",
    "Fossilized Bone Shard": "FossilizedBoneShard",
    "Fowl": "Fowl",
    "Fragile Bone Shard": "FragileBoneShard",
    "Fragment of Decarabian's Epic": "FragmentofDecarabiansEpic",
    "\"Fragments of Innocence\"": "FragmentsofInnocence",
    "Fragrant Cedar Wood": "FragrantCedarWood",
    "Frog": "Frog",
    "Gilded Scale": "GildedScale",
    "Glaze Lily": "GlazeLily",
    "Glaze Medaka": "GlazeMedaka",
    "Gloomy Statuette": "GloomyStatuette",
    "Golden Branch of a Distant Sea": "GoldenBranchofaDistantSea",
    "Golden Koi": "GoldenKoi",
    "Golden Raven Insignia": "GoldenRavenInsignia",
    "Grain of Aerosiderite": "GrainofAerosiderite",
    "Guide to Ballad": "GuidetoBallad",
    "Guide to Diligence": "GuidetoDiligence",
    "Guide to Elegance": "GuidetoElegance",
    "Guide to Freedom": "GuidetoFreedom",
    "Guide to Gold": "GuidetoGold",
    "Guide to Light": "GuidetoLight",
    "Guide to Prosperity": "GuidetoProsperity",
    "Guide to Resistance": "GuidetoResistance",
    "Guide to Transience": "GuidetoTransience",
    "Ham": "Ham",
    "Heavy Horn": "HeavyHorn",
    "Hellfire Butterfly": "HellfireButterfly",
    "Hero's Wit": "HerosWit",
    "Hoarfrost Core": "HoarfrostCore",
    "Horsetail": "Horsetail",
    "Hunter's Sacrificial Knife": "HuntersSacrificialKnife",
    "Hurricane Seed": "HurricaneSeed",
    "Inspector's Sacrificial Knife": "InspectorsSacrificialKnife",
    "Iron Chunk": "IronChunk",
    "Jade Branch of a Distant Sea": "JadeBranchofaDistantSea",
    "Jam": "Jam",
    "Jeweled Branch of a Distant Sea": "JeweledBranchofaDistantSea",
    "Jueyun Chili": "JueyunChili",
    "Juvenile Jade": "JuvenileJade",
    "Kageuchi Handguard": "KageuchiHandguard",
    "Lantern Fiber": "LanternFiber",
    "Lavender Melon": "LavenderMelon",
    "Ley Line Sprout": "LeyLineSprout",
    "Lieutenant's Insignia": "LieutenantsInsignia",
    "Lightning Prism": "LightningPrism",
    "Lizard Tail": "LizardTail",
    "Loach Pearl": "LoachPearl",
    "Lotus Head": "LotusHead",
    "Luminescent Spine": "LuminescentSpine",
    "Luminous Sands from Guyun": "LuminousSandsfromGuyun",
    "Lunged Stickleback": "LungedStickleback",
    "Lustrous Stone from Guyun": "LustrousStonefromGuyun",
    "Magical Crystal Chunk": "MagicalCrystalChunk",
    "Maple Wood": "MapleWood",
    "Marionette Core": "MarionetteCore",
    "Mask of the Kijin": "MaskoftheKijin",
    "Mask of the One-Horned": "MaskoftheOne-Horned",
    "Mask of the Tiger's Bite": "MaskoftheTigersBite",
    "Mask of the Wicked Lieutenant": "MaskoftheWickedLieutenant",
    "Matsutake": "Matsutake",
    "Medaka": "Medaka",
    "Milk": "Milk",
    "Mint": "Mint",
    "Mist Flower Corolla": "MistFlowerCorolla",
    "Mist Grass": "MistGrass",
    "Mist Grass Pollen": "MistGrassPollen",
    "Mist Grass Wick": "MistGrassWick",
    "Mist Veiled Gold Elixir": "MistVeiledGoldElixir",
    "Mist Veiled Lead Elixir": "MistVeiledLeadElixir",
    "Mist Veiled Mercury Elixir": "MistVeiledMercuryElixir",
    "Mist Veiled Primo Elixir": "MistVeiledPrimoElixir",
    "Molten Moment": "MoltenMoment",
    "Mora": "Mora",
    "Mushroom": "Mushroom",
    "Mystic Enhancement Ore": "MysticEnhancementOre",
    "Nagadus Emerald Chunk": "NagadusEmeraldChunk",
    "Nagadus Emerald Fragment": "NagadusEmeraldFragment",
    "Nagadus Emerald Gemstone": "NagadusEmeraldGemstone",
    "Nagadus Emerald Sliver": "NagadusEmeraldSliver",
    "Naku Weed": "NakuWeed",
    "Narukami's Affection": "NarukamisAffection",
    "Narukami's Joy": "NarukamisJoy",
    "Narukami's Valor": "NarukamisValor",
    "Narukami's Wisdom": "NarukamisWisdom",
    "Noctilucous Jade": "NoctilucousJade",
    "Northlander Bow Billet": "NorthlanderBowBillet",
    "Northlander Catalyst Billet": "NorthlanderCatalystBillet",
    "Northlander Claymore Billet": "NorthlanderClaymoreBillet",
    "Northlander Polearm Billet": "NorthlanderPolearmBillet",
    "Northlander Sword Billet": "NorthlanderSwordBillet",
    "Old Handguard": "OldHandguard",
    "Ominous Mask": "OminousMask",
    "Onikabuto": "Onikabuto",
    "Onion": "Onion",
    "Otogi Wood": "OtogiWood",
    "Pepper": "Pepper",
    "Perpetual Heart": "PerpetualHeart",
    "Philanemo Mushroom": "PhilanemoMushroom",
    "Philosophies of Ballad": "PhilosophiesofBallad",
    "Philosophies of Diligence": "PhilosophiesofDiligence",
    "Philosophies of Elegance": "PhilosophiesofElegance",
    "Philosophies of Freedom": "PhilosophiesofFreedom",
    "Philosophies of Gold": "PhilosophiesofGold",
    "Philosophies of Light": "PhilosophiesofLight",
    "Philosophies of Prosperity": "PhilosophiesofProsperity",
    "Philosophies of Resistance": "PhilosophiesofResistance",
    "Philosophies of Transience": "PhilosophiesofTransience",
    "Piece of Aerosiderite": "PieceofAerosiderite",
    "Pinecone": "Pinecone",
    "Pine Wood": "PineWood",
    "Plaustrite Shard": "PlaustriteShard",
    "Polarizing Prism": "PolarizingPrism",
    "Potato": "Potato",
    "Primogem": "Primogem",
    "Prithiva Topaz Chunk": "PrithivaTopazChunk",
    "Prithiva Topaz Fragment": "PrithivaTopazFragment",
    "Prithiva Topaz Gemstone": "PrithivaTopazGemstone",
    "Prithiva Topaz Sliver": "PrithivaTopazSliver",
    "Pufferfish": "Pufferfish",
    "Purple Shirakodai": "PurpleShirakodai",
    "Qingxin": "Qingxin",
    "Radish": "Radish",
    "Raimei Angelfish": "RaimeiAngelfish",
    "Raw Meat": "RawMeat",
    "Recruit's Insignia": "RecruitsInsignia",
    "Red Dye": "RedDye",
    "Relic from Guyun": "RelicfromGuyun",
    "Rice": "Rice",
    "Riftborn Regalia": "RiftbornRegalia",
    "Ring of Boreas": "RingofBoreas",
    "Rusty Koi": "RustyKoi",
    "Sakura Bloom": "SakuraBloom",
    "Salt": "Salt",
    "Sandbearer Wood": "SandbearerWood",
    "Sango Pearl": "SangoPearl",
    "Sausage": "Sausage",
    "Scattered Piece of Decarabian's Dream": "ScatteredPieceofDecarabiansDream",
    "Sea Ganoderma": "SeaGanoderma",
    "Seagrass": "Seagrass",
    "Sealed Scroll": "SealedScroll",
    "Sergeant's Insignia": "SergeantsInsignia",
    "Shackles of the Dandelion Gladiator": "ShacklesoftheDandelionGladiator",
    "Shadow of the Warrior": "ShadowoftheWarrior",
    "Shard of a Foul Legacy": "ShardofaFoulLegacy",
    "Sharp Arrowhead": "SharpArrowhead",
    "Shimmering Nectar": "ShimmeringNectar",
    "Shivada Jade Chunk": "ShivadaJadeChunk",
    "Shivada Jade Fragment": "ShivadaJadeFragment",
    "Shivada Jade Gemstone": "ShivadaJadeGemstone",
    "Shivada Jade Sliver": "ShivadaJadeSliver",
    "Shrimp Meat": "ShrimpMeat",
    "Silk Flower": "SilkFlower",
    "Silver Lotus": "SilverLotus",
    "Silver Raven Insignia": "SilverRavenInsignia",
    "Slime Concentrate": "SlimeConcentrate",
    "Slime Condensate": "SlimeCondensate",
    "Slime Secretions": "SlimeSecretions",
    "Small Lamp Grass": "SmallLampGrass",
    "Smoked Fish": "SmokedFish",
    "Smoked Fowl": "SmokedFowl",
    "Smoldering Pearl": "SmolderingPearl",
    "Snapdragon": "Snapdragon",
    "Snowstrider": "Snowstrider",
    "Spectral Heart": "SpectralHeart",
    "Spectral Husk": "SpectralHusk",
    "Spectral Nucleus": "SpectralNucleus",
    "Spirit Locket of Boreas": "SpiritLocketofBoreas",
    "Stained Mask": "StainedMask",
    "Starconch": "Starconch",
    "Starsilver": "Starsilver",
    "Storm Beads": "StormBeads",
    "Strange Tooth": "StrangeTooth",
    "Sturdy Bone Shard": "SturdyBoneShard",
    "Sugar": "Sugar",
    "Sunsettia": "Sunsettia",
    "Sweet Flower": "SweetFlower",
    "Sweet-Flower Medaka": "Sweet-FlowerMedaka",
    "Tail of Boreas": "TailofBoreas",
    "Teachings of Ballad": "TeachingsofBallad",
    "Teachings of Diligence": "TeachingsofDiligence",
    "Teachings of Elegance": "TeachingsofElegance",
    "Teachings of Freedom": "TeachingsofFreedom",
    "Teachings of Gold": "TeachingsofGold",
    "Teachings of Light": "TeachingsofLight",
    "Teachings of Prosperity": "TeachingsofProsperity",
    "Teachings of Resistance": "TeachingsofResistance",
    "Teachings of Transience": "TeachingsofTransience",
    "Tea-Colored Shirakodai": "Tea-ColoredShirakodai",
    "\"The Visible Winds\"": "TheVisibleWinds",
    "Tile of Decarabian's Tower": "TileofDecarabiansTower",
    "Tofu": "Tofu",
    "Tomato": "Tomato",
    "Treasure Hoarder Insignia": "TreasureHoarderInsignia",
    "Tusk of Monoceros Caeli": "TuskofMonocerosCaeli",
    "Unagi Meat": "UnagiMeat",
    "Vajrada Amethyst Chunk": "VajradaAmethystChunk",
    "Vajrada Amethyst Fragment": "VajradaAmethystFragment",
    "Vajrada Amethyst Gemstone": "VajradaAmethystGemstone",
    "Vajrada Amethyst Sliver": "VajradaAmethystSliver",
    "Valberry": "Valberry",
    "Varunada Lazurite Chunk": "VarunadaLazuriteChunk",
    "Varunada Lazurite Fragment": "VarunadaLazuriteFragment",
    "Varunada Lazurite Gemstone": "VarunadaLazuriteGemstone",
    "Varunada Lazurite Sliver": "VarunadaLazuriteSliver",
    "Vayuda Turquoise Chunk": "VayudaTurquoiseChunk",
    "Vayuda Turquoise Fragment": "VayudaTurquoiseFragment",
    "Vayuda Turquoise Gemstone": "VayudaTurquoiseGemstone",
    "Vayuda Turquoise Sliver": "VayudaTurquoiseSliver",
    "Venomspine Fish": "VenomspineFish",
    "Violetgrass": "Violetgrass",
    "Vitalized Dragontooth": "VitalizedDragontooth",
    "Wanderer's Advice": "WanderersAdvice",
    "Weathered Arrowhead": "WeatheredArrowhead",
    "Wheat": "Wheat",
    "White Iron Chunk": "WhiteIronChunk",
    "Whopperflower Nectar": "WhopperflowerNectar",
    "Wick Material": "WickMaterial",
    "Windwheel Aster": "WindwheelAster",
    "Wolfhook": "Wolfhook",
    "Yellow Dye": "YellowDye",
    "Yumemiru Wood": "YumemiruWood"
}
